controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    left_rear_wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    right_rear_wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    left_front_wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    right_front_wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    left_steering_hinge_position_controller:
      type: forward_command_controller/ForwardCommandController

    right_steering_hinge_position_controller:
      type: forward_command_controller/ForwardCommandController

left_rear_wheel_velocity_controller:
  ros__parameters:
    joints:
      - left_rear_wheel_joint

right_rear_wheel_velocity_controller:
  ros__parameters:
    joints:
      - right_rear_wheel_joint

left_front_wheel_velocity_controller:
  ros__parameters:
    joints:
      - left_front_wheel_joint

right_front_wheel_velocity_controller:
  ros__parameters:
    joints:
      - right_front_wheel_joint

left_steering_hinge_position_controller:
  ros__parameters:
    joints:
      - left_steering_hinge_joint
    interface_name: position

right_steering_hinge_position_controller:
  ros__parameters:
    joints:
      - right_steering_hinge_joint
    interface_name: position
